#!/usr/bin/env python3

import argparse

import helpers as hp

CMD_DELETE = "kubectl delete {api} -n {namespace} "


def main(opts):
    hp.acknowledge_deletion()

    if not opts.no_cscs:
        namespaces = hp.STANDARD_NAMESPACES
    else:
        namespaces = ["kafka-producers", "ospl-daemon"]
    if not opts.clean_daemons:
        del namespaces[namespaces.index("ospl-daemon")]
    if opts.no_kp:
        del namespaces[namespaces.index("kafka-producers")]

    for namespace in namespaces:
        if namespace == "love":
            for api in hp.API_MAPPING[namespace]:
                command = CMD_DELETE.format(
                    api=api, namespace=namespace
                )
                if opts.love_dds_only:
                    if api == "hpa":
                        continue
                    if api == "deployment":
                        command += "-l app.kubernetes.io/name=love-producer"
                    if api == "job":
                        command += "-l csc=love-commander"
                else:
                    command += "--all"
                if opts.no_run:
                    print(command)
                else:
                    output = hp.run_cmd(command)
                    print(output)
        else:
            command = CMD_DELETE.format(
                api=hp.API_MAPPING[namespace], namespace=namespace
            )
            if namespace == "uws":
                command = command.split()
                command.append("-l")
                command.append("csc in (atocps, ccocps)")
            else:
                command += "--all"
            if opts.no_run:
                print(command)
            else:
                output = hp.run_cmd(command)
                print(output)


if __name__ == "__main__":
    description = ["This program cleans up all deployed systems. The cleanup"]
    description.append("of the OSPL daemons is optional.")
    parser = argparse.ArgumentParser(
        description=" ".join(description),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    parser.add_argument(
        "-d",
        "--clean-daemons",
        dest="clean_daemons",
        action="store_true",
        help="Clean up the OSPL daemons.",
    )
    parser.add_argument("--no-run", action="store_true", help="Do not run script, just print commands.")

    parser.add_argument("--no-kp", action="store_true", help="Don't shutdown the kafka producers.")

    parser.add_argument("--no-cscs", action="store_true", help="Don't shutdown CSC namespaces.")

    parser.add_argument("--love-dds-only", action="store_true", help="Delete on DDS related APIs for LOVE.")

    args = parser.parse_args()
    main(args)
