#!/usr/bin/env python3

import argparse

import helpers as hp

CMD_DELETE_ALL = "kubectl delete {api} -n {namespace} --all"


def main(opts):
    namespaces = hp.STANDARD_NAMESPACES
    if not opts.clean_daemons:
        del namespaces[namespaces.index("ospl-daemon")]

    for namespace in namespaces:
        command = CMD_DELETE_ALL.format(api=hp.API_MAPPING[namespace],
                                        namespace=namespace)
        output = hp.run_cmd(command)
        print(output)


if __name__ == '__main__':
    description = ["This program cleans up all deployed systems. The cleanup"]
    description.append("of the OSPL daemons is optional.")
    parser = argparse.ArgumentParser(description=" ".join(description),
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    parser.add_argument("-d", "--clean-daemons", dest="clean_daemons", action="store_true",
                        help="Clean up the OSPL daemons.")

    args = parser.parse_args()
    main(args)
