#!/usr/bin/env python3

import argparse

import helpers as hp

CMD_DELETE = "kubectl delete {api} -n {namespace} "


def main(opts):
    hp.acknowledge_deletion()

    if not opts.no_cscs:
        namespaces = hp.STANDARD_NAMESPACES
    else:
        namespaces = []
        if opts.namespaces is not None:
            ns_list = opts.namespaces.split(",")
            for ns in ns_list:
                namespaces.insert(0, ns)

    for namespace in namespaces:
        if namespace == "love":
            if opts.no_love:
                continue
            for api in hp.API_MAPPING[namespace]:
                command = CMD_DELETE.format(
                    api=api, namespace=namespace
                )
                
                command += "--all"
                
                if opts.no_run:
                    print(command)
                else:
                    output = hp.run_cmd(command)
                    print(output)
        else:
            command = CMD_DELETE.format(
                api=hp.API_MAPPING[namespace], namespace=namespace
            )
            if namespace == "uws":
                command = command.split()
                command.append("-l")
                command.append("csc-class=ocps")
            else:
                command += "--all"
            if opts.no_run:
                print(command)
            else:
                output = hp.run_cmd(command)
                print(output)


if __name__ == "__main__":
    description = ["This program cleans up all deployed systems."]
    parser = argparse.ArgumentParser(
        description=" ".join(description),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    parser.add_argument("--no-run", action="store_true", help="Do not run script, just print commands.")

    parser.add_argument("--no-cscs", action="store_true", help="Don't shutdown CSC namespaces.")

    parser.add_argument("--no-love", action="store_true", help="Don't shutdown LOVE systems.")

    parser.add_argument(
        "--namespaces",
        help="Comma-delimited list of namespaces to clean up. Used in conjunction with --no-cscs option."
    )

    args = parser.parse_args()
    main(args)
