#!/usr/bin/env python3

import argparse

import helpers as hp

CMD_DELETE_ALL = "kubectl delete ns -l argocd.argoproj.io/instance=nublado-users"

def main(opts):
    hp.acknowledge_deletion()
    output = hp.run_cmd(CMD_DELETE_ALL)
    print(output)


if __name__ == '__main__':
    description = ["This program cleans up Nublado pods."]
    parser = argparse.ArgumentParser(
        description=" ".join(description),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    args = parser.parse_args()
    main(args)
