#!/usr/bin/env python3

import argparse

import helpers as hp


def main(opts):
    command = hp.GET_PODS_CMD + " --all-namespaces"
    output = hp.run_cmd(command)
    print(output)


if __name__ == '__main__':
    description = ["This program lists all pods on Kuberneted."]
    parser = argparse.ArgumentParser(description=" ".join(description),
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    args = parser.parse_args()
    main(args)
