#!/usr/bin/env python3

import argparse

import helpers as hp


def main(opts):
    namespaces = hp.STANDARD_NAMESPACES
    del namespaces[namespaces.index("ospl-daemon")]

    for namespace in namespaces:
        command = hp.GET_PODS_CMD + f" -n {namespace}"
        output = hp.run_cmd(command, as_lines=True)
        for line in output:
            if line == "":
                continue
            values = line.strip().split()
            if values[0] == "NODE":
                continue
            if opts.node_name not in values[0]:
                continue
            print(values[1])


if __name__ == "__main__":
    description = ["This program lists all pods in the standard deployment"]
    description.append("on a given node except for the OSPL daemons.")
    parser = argparse.ArgumentParser(
        description=" ".join(description),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    parser.add_argument("node_name", help="Name of the node to clean.")

    args = parser.parse_args()
    main(args)
