#!/usr/bin/env python3

import argparse

import helpers as hp

CMD_DELETE = "kubectl delete {resource} {name} -n {namespace} "
CMD_SCALE_DOWN = "kubectl scale deployment {name} {selector} --replicas=0 -n {namespace}"
CMD_ANNOTATE = "kubectl annotate --overwrite {kind} {name} {annotation} -n {namespace}"

def main(opts):
    hp.acknowledge_deletion()
    namespace = "sasquatch"
    commands = [
        CMD_SCALE_DOWN.format(name="sasquatch-schema-registry", selector="", namespace=namespace),
        CMD_SCALE_DOWN.format(name="", selector="--selector app.kubernetes.io/name=sasquatch-telegraf", namespace=namespace),
        CMD_ANNOTATE.format(kind="Kafka", name="sasquatch", annotation="strimzi.io/pause-reconciliation=\"true\"", namespace=namespace),
        CMD_DELETE.format(resource="StrimziPodSet", name="sasquatch-kafka-local-storage", namespace=namespace),
        CMD_DELETE.format(resource="StrimziPodSet", name="sasquatch-controller", namespace=namespace),
    ]

    for command in commands:
        if opts.no_run:
            print(command)
        else:
            output = hp.run_cmd(command)
            print(output)

if __name__ == "__main__":
    description = ["This program shuts down Kafka gracefully."]
    parser = argparse.ArgumentParser(
        description=" ".join(description),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    parser.add_argument("--no-run", action="store_true", help="Do not run script, just print commands.")

    args = parser.parse_args()
    main(args)
