#!/usr/bin/env python3

import argparse

import helpers as hp


def main(opts):
    print("Staring Kafka...")
    namespace = "sasquatch"
    commands=[
        (hp.CMD_ANNOTATE.format(kind="Kafka", name="sasquatch", annotation="strimzi.io/pause-reconciliation=\"false\"", namespace=namespace), False),
        (hp.CMD_WAIT.format(selector="-l strimzi.io/pod-set-name=sasquatch-kafka-local-storage", timeout="600s", namespace=namespace), True),
        (hp.CMD_WAIT.format(selector="-l strimzi.io/pod-set-name=sasquatch-controller", timeout="600s", namespace=namespace), True),
        (hp.CMD_SCALE.format(name="sasquatch-schema-registry", selector="", replicas="3", namespace=namespace), False),
        (hp.CMD_SCALE.format(name="", selector="--selector app.kubernetes.io/name=sasquatch-telegraf", replicas="1", namespace=namespace), False),
    ]

    if opts.no_run:
        for command, _ in commands:
            print(command)
    else:
        for command, check in commands:
            output = hp.run_cmd(command, check=check)
            print(output)

if __name__ == "__main__":
    description = ["This program restarts Kafka."]
    parser = argparse.ArgumentParser(
        description=" ".join(description),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    parser.add_argument("--no-run", action="store_true", help="Do not run script, just print commands.")

    args = parser.parse_args()
    main(args)
