#!/usr/bin/env python3

import argparse

import helpers as hp


def main(opts):
    command = hp.GET_PODS_CMD + " -n ospl-daemon"
    output = hp.run_cmd(command)
    print(output)


if __name__ == "__main__":
    description = ["This program lists all of the OSPL daemons."]
    parser = argparse.ArgumentParser(
        description=" ".join(description),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    args = parser.parse_args()
    main(args)
